# Generated by Django 4.1.7 on 2024-08-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, choices=[('E', 'English'), ('S', 'Spanish'), ('C', 'Chinese'), ('F', 'French'), ('G', 'German'), ('R', 'Russian'), ('J', 'Japanese'), ('I', 'Italian'), ('P', 'Portuguese'), ('A', 'Arabic'), ('K', 'Korean'), ('H', 'Hindi'), ('D', 'Dutch'), ('W', 'Swedish'), ('T', 'Turkish'), ('Gr', 'Greek')], max_length=32, null=True),
        ),
    ]
