# Generated by Django 4.1.7 on 2024-08-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zodiac',
            field=models.CharField(blank=True, choices=[('Ari', 'Овен'), ('Tau', 'Телец'), ('Gem', 'Близнецы'), ('Can', 'Рак'), ('Leo', 'Лев'), ('Vir', 'Дева'), ('Lib', 'Весы'), ('Sco', 'Скорпион'), ('Sag', 'Стрелец'), ('Cap', 'Козерог'), ('Aqu', 'Водолей'), ('Pis', 'Рыбы')], max_length=32, null=True),
        ),
    ]
