# Generated by Django 4.1.7 on 2024-08-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_zodiac'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
