# Generated by Django 5.0.6 on 2024-08-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_city_alter_user_height_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('A', 'All')], default='A', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='interest_gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('A', 'All')], default='A', max_length=3),
        ),
    ]
