# Generated by Django 5.0.6 on 2024-08-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_gender_user_interest_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bidth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('A', 'All')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('A', 'All')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
