# Generated by Django 5.0.6 on 2024-08-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_bidth_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('L', 'Love'), ('R', 'Romantice'), ('O', 'Obzhenie')], max_length=1, null=True),
        ),
    ]
