# Generated by Django 4.1.7 on 2024-08-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_interest_userinterest_userfilters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='interest',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
