# Generated by Django 5.0.6 on 2024-08-03 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('users', '0007_user_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery'),
        ),
    ]
