# Generated by Django 5.0.6 on 2024-08-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
