# Generated by Django 4.1.7 on 2024-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='childrens',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('S', 'Среднее'), ('M', 'Магистр'), ('V', 'Высшее')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orientation',
            field=models.CharField(blank=True, choices=[('H', 'Гетеросексуал'), ('G', 'Гей / Лесбиянка'), ('B', 'Бисексуал'), ('A', 'Асексуал'), ('D', 'Демисексуал'), ('P', 'Пансексуал')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personality',
            field=models.CharField(blank=True, choices=[('E', 'Экстраверт'), ('I', 'Интроверт'), ('S', 'Что-то между')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Soso')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=32, null=True),
        ),
    ]
