# Generated by Django 4.1.7 on 2024-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_childrens_user_education_user_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=32, null=True),
        ),
    ]
